### ISSUE TITLE
help 

### ISSUE THREAD

**Issue by NoX010** [pitz143/Yaaro#1]
its showing me this 

hey
what are you

    Error 263 for command:
        open test.mp3
    The specified device is not open or is not recognized by MCI.

    Error 263 for command:
        close test.mp3
    The specified device is not open or is not recognized by MCI.
Failed to close the file: test.mp3
Traceback (most recent call last):
  File "C:\Users\smitc\OneDrive\Desktop\new_1\venv\assistance.py", line 99, in <module>
    execute_voice_command(command)
  File "C:\Users\smitc\OneDrive\Desktop\new_1\venv\assistance.py", line 42, in execute_voice_command
    audio_playback("i am jarvis your voice assistance system")
  File "C:\Users\smitc\OneDrive\Desktop\new_1\venv\assistance.py", line 36, in audio_playback
    playsound.playsound(filename)
  File "C:\Users\smitc\OneDrive\Desktop\new_1\venv\lib\site-packages\playsound.py", line 72, in _playsoundWin
    winCommand(u'open {}'.format(sound))
  File "C:\Users\smitc\OneDrive\Desktop\new_1\venv\lib\site-packages\playsound.py", line 64, in winCommand
    raise PlaysoundException(exceptionMessage)
playsound.PlaysoundException: 
    Error 263 for command:
        open test.mp3
    The specified device is not open or is not recognized by MCI.

**Comment by pitz143** [comment]
The program must create test.mp3 did you install pip install pyaudio==0.2.11

**Comment by pitz143** [comment]
And also you have to say "hey Jarvis what are you"  not just "hey"
